version: '2'
services:
  odoo16_ee_ztyres:
    container_name: odoo16_ee_ztyres_web
    image: jrmpacheco/odoo16_ee_ztyres:1.0.2
    user: odoo
    ports:
      - "9069:8069" # Normal Port
      - "9090:8090" # Testing Port
      - "9072:8072" # Longpolling Port
      - "9001:8001" # Debug Port
    tty: true
    # command: --
    volumes:
      - ./etc:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - /ZTYRES/FILESTORE:/var/lib/odoo/.local/share/Odoo
    restart: always