version: '2'
services:
  odoo16_ee_ztyres:
    container_name: odoo16_ee_ztyres
    image: jrmpacheco/odoo16_ee_ztyres
    user: odoo
    ports:
      - "8069:8069" # Normal Port
      - "8090:8090" # Testing Port
      - "8071:8071" # Longpolling Port
      - "8001:8001" # Debug Port
    tty: true
    # command: --
    volumes:
      - ./etc:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./out_files:/mnt/out_files
      - ../Filestore:/var/lib/odoo/.local/share/Odoo
    restart: always